"""
MTGroup VPN Ultimate — Alembic Migration Tests

Covers the two things that actually break deployments:

1. **Schema drift.** `alembic check` must report nothing, i.e. the
   migration history and `Base.metadata` describe the same database. If
   someone edits a model without generating a migration, this fails —
   which is the whole point of having migrations, since the old
   `create_all()` would have silently ignored the new column on any
   existing install and then crashed with "no such column".
2. **Adopting a pre-Alembic database.** Deployments created before
   migrations existed have the tables but no `alembic_version`. Booting
   must stamp and upgrade them in place, not try to re-create tables and
   not lose data.
"""

from __future__ import annotations

import pytest
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import create_async_engine

from backend.app.models import Base, User, create_session_factory, init_db


def _url(tmp_path, name: str) -> str:
    return f"sqlite+aiosqlite:///{(tmp_path / name).as_posix()}"


class TestSchemaMatchesModels:
    def test_alembic_check_reports_no_drift(self, tmp_path):
        """The migrations must fully reproduce Base.metadata."""
        from alembic import command
        from alembic.util.exc import AutogenerateDiffsDetected

        from backend.app.models import _alembic_config

        url = _url(tmp_path, "drift.db")
        cfg = _alembic_config(url)
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(
                "Models and migrations have diverged — generate a migration "
                f"with `alembic revision --autogenerate`:\n{exc}"
            )


class TestFreshDatabase:
    @pytest.mark.asyncio
    async def test_migrates_from_scratch_and_is_usable(self, tmp_path):
        engine = create_async_engine(_url(tmp_path, "fresh.db"))
        try:
            await init_db(engine)
            async with create_session_factory(engine)() as session:
                session.add(User(username="fresh", hashed_password="x"))
                await session.commit()
                count = (await session.execute(text("select count(*) from users"))).scalar_one()
                version = (await session.execute(text("select version_num from alembic_version"))).scalar_one()
            assert count == 1
            assert version  # stamped at head
        finally:
            await engine.dispose()


class TestPreAlembicDatabaseAdoption:
    @pytest.mark.asyncio
    async def test_existing_data_survives_adoption(self, tmp_path):
        url = _url(tmp_path, "legacy.db")

        # Build a database the *old* way — tables, data, no alembic_version.
        legacy = create_async_engine(url)
        try:
            async with legacy.begin() as conn:
                await conn.run_sync(Base.metadata.create_all)
            async with create_session_factory(legacy)() as session:
                session.add(User(username="legacy-user", hashed_password="x"))
                await session.commit()
        finally:
            await legacy.dispose()

        # Booting must adopt it rather than failing on "table already exists".
        engine = create_async_engine(url)
        try:
            await init_db(engine)
            async with create_session_factory(engine)() as session:
                user = (
                    await session.execute(select(User).where(User.username == "legacy-user"))
                ).scalar_one_or_none()
                version = (await session.execute(text("select version_num from alembic_version"))).scalar_one()
            assert user is not None, "adoption destroyed pre-existing data"
            assert version
        finally:
            await engine.dispose()

    @pytest.mark.asyncio
    async def test_booting_twice_is_a_noop(self, tmp_path):
        url = _url(tmp_path, "twice.db")
        for _ in range(2):
            engine = create_async_engine(url)
            try:
                await init_db(engine)
            finally:
                await engine.dispose()

        engine = create_async_engine(url)
        try:
            async with create_session_factory(engine)() as session:
                versions = (await session.execute(text("select version_num from alembic_version"))).scalars().all()
            assert len(versions) == 1  # exactly one row, not duplicated
        finally:
            await engine.dispose()


class TestMigrationIsReversible:
    def test_upgrade_then_downgrade_leaves_no_tables(self, tmp_path):
        from alembic import command

        from backend.app.models import _alembic_config

        cfg = _alembic_config(_url(tmp_path, "rev.db"))
        command.upgrade(cfg, "head")
        command.downgrade(cfg, "base")

        import sqlite3

        conn = sqlite3.connect(tmp_path / "rev.db")
        try:
            names = {r[0] for r in conn.execute("select name from sqlite_master where type='table'")}
        finally:
            conn.close()
        # alembic_version legitimately remains; nothing else should.
        assert names <= {"alembic_version"}, f"downgrade left tables behind: {names}"


class TestUniquenessStillEnforced:
    @pytest.mark.asyncio
    async def test_duplicate_username_is_rejected(self, tmp_path):
        """
        The column-level `unique=True` was removed from six columns that
        already declared a *named* UniqueConstraint in `__table_args__`
        (it produced duplicate DDL and permanent `alembic check` drift).
        Uniqueness must still be enforced by the named constraint.
        """
        from sqlalchemy.exc import IntegrityError

        engine = create_async_engine(_url(tmp_path, "uniq.db"))
        try:
            await init_db(engine)
            factory = create_session_factory(engine)
            async with factory() as session:
                session.add(User(username="dup", hashed_password="x"))
                await session.commit()
            with pytest.raises(IntegrityError):
                async with factory() as session:
                    session.add(User(username="dup", hashed_password="y"))
                    await session.commit()
        finally:
            await engine.dispose()
