"""
MTGroup VPN Ultimate — Alembic Migration Tests

Covers the two things that actually break deployments:

1. **Schema drift.** `alembic check` must report nothing, i.e. the
   migration history and `Base.metadata` describe the same database. If
   someone edits a model without generating a migration, this fails —
   which is the whole point of having migrations, since the old
   `create_all()` would have silently ignored the new column on any
   existing install and then crashed with "no such column".
2. **Adopting a pre-Alembic database.** Deployments created before
   migrations existed have the tables but no `alembic_version`. Booting
   must stamp and upgrade them in place, not try to re-create tables and
   not lose data.
"""

from __future__ import annotations

import pytest
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import create_async_engine

from backend.app.models import Base, User, create_session_factory, init_db


def _url(tmp_path, name: str) -> str:
    return f"sqlite+aiosqlite:///{(tmp_path / name).as_posix()}"


class TestSchemaMatchesModels:
    def test_alembic_check_reports_no_drift(self, tmp_path):
        """The migrations must fully reproduce Base.metadata."""
        from alembic import command
        from alembic.util.exc import AutogenerateDiffsDetected

        from backend.app.models import _alembic_config

        url = _url(tmp_path, "drift.db")
        cfg = _alembic_config(url)
        command.upgrade(cfg, "head")
        try:
            command.check(cfg)
        except AutogenerateDiffsDetected as exc:
            pytest.fail(
                "Models and migrations have diverged — generate a migration "
                f"with `alembic revision --autogenerate`:\n{exc}"
            )


class TestFreshDatabase:
    @pytest.mark.asyncio
    async def test_migrates_from_scratch_and_is_usable(self, tmp_path):
        engine = create_async_engine(_url(tmp_path, "fresh.db"))
        try:
            await init_db(engine)
            async with create_session_factory(engine)() as session:
                session.add(User(username="fresh", hashed_password="x"))
                await session.commit()
                count = (await session.execute(text("select count(*) from users"))).scalar_one()
                version = (await session.execute(text("select version_num from alembic_version"))).scalar_one()
            assert count == 1
            assert version  # stamped at head
        finally:
            await engine.dispose()


class TestPreAlembicDatabaseAdoption:
    @pytest.mark.asyncio
    async def test_existing_data_survives_adoption(self, tmp_path):
        url = _url(tmp_path, "legacy.db")

        # Build a database the *old* way — tables, data, no alembic_version.
        legacy = create_async_engine(url)
        try:
            async with legacy.begin() as conn:
                await conn.run_sync(Base.metadata.create_all)
            async with create_session_factory(legacy)() as session:
                session.add(User(username="legacy-user", hashed_password="x"))
                await session.commit()
        finally:
            await legacy.dispose()

        # Booting must adopt it rather than failing on "table already exists".
        engine = create_async_engine(url)
        try:
            await init_db(engine)
            async with create_session_factory(engine)() as session:
                user = (
                    await session.execute(select(User).where(User.username == "legacy-user"))
                ).scalar_one_or_none()
                version = (await session.execute(text("select version_num from alembic_version"))).scalar_one()
            assert user is not None, "adoption destroyed pre-existing data"
            assert version
        finally:
            await engine.dispose()

    @pytest.mark.asyncio
    async def test_outdated_unversioned_database_is_brought_forward(self, tmp_path):
        """
        The case that actually happens on a real deployment: an unversioned
        database whose schema predates a migration.

        An unversioned database records nothing about which schema it
        corresponds to, so adoption picks the stamp by inspecting what is
        there. Stamping head here would skip the migration and leave the
        table permanently missing; stamping the initial revision on an
        already-current database would instead replay it and fail on
        "table already exists". Both directions are covered — this test and
        `test_existing_data_survives_adoption`.
        """
        import sqlite3

        from sqlalchemy import inspect as sa_inspect

        url = _url(tmp_path, "outdated.db")
        db_path = tmp_path / "outdated.db"

        # Build a current-schema database, then remove a table added by a
        # later migration and strip the version marker, so it looks like an
        # older unversioned install.
        seed = create_async_engine(url)
        try:
            async with seed.begin() as conn:
                await conn.run_sync(Base.metadata.create_all)
        finally:
            await seed.dispose()

        conn = sqlite3.connect(db_path)
        try:
            # Undo *everything* the latest migration introduced, not just the
            # table — a real pre-migration database would have none of it,
            # and leaving the columns behind would construct a half-migrated
            # state that no revision corresponds to.
            conn.execute("DROP TABLE IF EXISTS wireguard_peers")
            conn.execute("ALTER TABLE nodes DROP COLUMN amnezia_subnet")
            conn.execute("ALTER TABLE nodes DROP COLUMN amnezia_server_public_key")
            conn.execute("DROP TABLE IF EXISTS alembic_version")
            conn.commit()
        finally:
            conn.close()

        engine = create_async_engine(url)
        try:
            await init_db(engine)
            async with engine.connect() as connection:
                tables = await connection.run_sync(lambda c: set(sa_inspect(c).get_table_names()))
        finally:
            await engine.dispose()

        assert "wireguard_peers" in tables, "adoption failed to apply the pending migration"

    @pytest.mark.asyncio
    async def test_booting_twice_is_a_noop(self, tmp_path):
        url = _url(tmp_path, "twice.db")
        for _ in range(2):
            engine = create_async_engine(url)
            try:
                await init_db(engine)
            finally:
                await engine.dispose()

        engine = create_async_engine(url)
        try:
            async with create_session_factory(engine)() as session:
                versions = (await session.execute(text("select version_num from alembic_version"))).scalars().all()
            assert len(versions) == 1  # exactly one row, not duplicated
        finally:
            await engine.dispose()


class TestUpgradeAgainstPopulatedTables:
    def test_every_revision_applies_to_a_database_with_rows(self, tmp_path):
        """
        Walk the migration chain one revision at a time against a database
        that already contains data, rather than only ever testing the
        empty-database path.

        This catches the single most common way a migration breaks a live
        deployment: adding a NOT NULL column without a `server_default`.
        SQLAlchemy's `default=` is applied in Python on INSERT, so the
        database still sees NULL and `ALTER TABLE ... ADD COLUMN ... NOT
        NULL` fails with "Cannot add a NOT NULL column with default value
        NULL" — but only on a table that has rows, which is exactly the
        case a fresh-database test never exercises. That failure was real
        and was caught here first.
        """
        import sqlite3

        from alembic import command
        from alembic.script import ScriptDirectory

        from backend.app.models import _alembic_config

        db_path = tmp_path / "populated.db"
        cfg = _alembic_config(f"sqlite+aiosqlite:///{db_path.as_posix()}")
        script = ScriptDirectory.from_config(cfg)

        revisions = [rev.revision for rev in reversed(list(script.walk_revisions()))]
        assert revisions, "no migrations found"

        for revision in revisions:
            command.upgrade(cfg, revision)

            # Seed one row into every table that's empty, so the *next*
            # revision has to cope with existing data.
            conn = sqlite3.connect(db_path)
            try:
                conn.execute("PRAGMA foreign_keys = OFF")
                tables = [
                    r[0]
                    for r in conn.execute(
                        "select name from sqlite_master where type='table' "
                        "and name not like 'sqlite_%' and name != 'alembic_version'"
                    )
                ]
                for table in tables:
                    # nosec B608 below: table/column names come from this
                    # test's own temp database via sqlite_master, never from
                    # user input, and sqlite cannot parameterise identifiers.
                    if conn.execute(f"select count(*) from '{table}'").fetchone()[0]:  # nosec B608
                        continue
                    cols = [
                        (r[1], r[2], r[4])
                        for r in conn.execute(f"pragma table_info('{table}')")
                        if r[3] and r[5] == 0  # NOT NULL, not part of the PK
                    ]
                    needed = [(n, t) for n, t, default in cols if default is None]
                    if not needed:
                        conn.execute(f"insert into '{table}' default values")  # nosec B608
                        continue
                    names = ", ".join(f"'{n}'" for n, _ in needed)
                    values = ", ".join(
                        "0" if any(k in t.upper() for k in ("INT", "REAL", "FLOAT", "BOOL", "NUMERIC"))
                        else "'2026-01-01 00:00:00'" if "DATE" in t.upper() or "TIME" in t.upper()
                        else f"'seed-{i}'"
                        for i, (_, t) in enumerate(needed)
                    )
                    try:
                        conn.execute(f"insert into '{table}' ({names}) values ({values})")  # nosec B608
                    except sqlite3.IntegrityError:
                        pass  # enum/FK constraints we can't satisfy generically
                conn.commit()
            finally:
                conn.close()


class TestMigrationIsReversible:
    def test_upgrade_then_downgrade_leaves_no_tables(self, tmp_path):
        from alembic import command

        from backend.app.models import _alembic_config

        cfg = _alembic_config(_url(tmp_path, "rev.db"))
        command.upgrade(cfg, "head")
        command.downgrade(cfg, "base")

        import sqlite3

        conn = sqlite3.connect(tmp_path / "rev.db")
        try:
            names = {r[0] for r in conn.execute("select name from sqlite_master where type='table'")}
        finally:
            conn.close()
        # alembic_version legitimately remains; nothing else should.
        assert names <= {"alembic_version"}, f"downgrade left tables behind: {names}"


class TestUniquenessStillEnforced:
    @pytest.mark.asyncio
    async def test_duplicate_username_is_rejected(self, tmp_path):
        """
        The column-level `unique=True` was removed from six columns that
        already declared a *named* UniqueConstraint in `__table_args__`
        (it produced duplicate DDL and permanent `alembic check` drift).
        Uniqueness must still be enforced by the named constraint.
        """
        from sqlalchemy.exc import IntegrityError

        engine = create_async_engine(_url(tmp_path, "uniq.db"))
        try:
            await init_db(engine)
            factory = create_session_factory(engine)
            async with factory() as session:
                session.add(User(username="dup", hashed_password="x"))
                await session.commit()
            with pytest.raises(IntegrityError):
                async with factory() as session:
                    session.add(User(username="dup", hashed_password="y"))
                    await session.commit()
        finally:
            await engine.dispose()
