"""add wireguard peers and node amnezia subnet

Revision ID: 7f3c040beaf9
Revises: c5707e6531fc
Create Date: 2026-08-10 23:39:54.962962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3c040beaf9'
down_revision: Union[str, Sequence[str], None] = 'c5707e6531fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wireguard_peers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('public_key', sa.String(length=128), nullable=False),
    sa.Column('assigned_ip', sa.String(length=64), nullable=False),
    sa.Column('is_synced_to_node', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'assigned_ip', name='uq_wg_peer_node_ip'),
    sa.UniqueConstraint('subscription_id', 'node_id', name='uq_wg_peer_sub_node')
    )
    with op.batch_alter_table('wireguard_peers', schema=None) as batch_op:
        batch_op.create_index('ix_wg_peer_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_wg_peer_subscription_id', ['subscription_id'], unique=False)

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amnezia_server_public_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('amnezia_subnet', sa.String(length=64), server_default='10.8.0.0/24', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('amnezia_subnet')
        batch_op.drop_column('amnezia_server_public_key')

    with op.batch_alter_table('wireguard_peers', schema=None) as batch_op:
        batch_op.drop_index('ix_wg_peer_subscription_id')
        batch_op.drop_index('ix_wg_peer_node_id')

    op.drop_table('wireguard_peers')
    # ### end Alembic commands ###
