"""initial schema

Revision ID: c5707e6531fc
Revises: 
Create Date: 2026-08-10 23:20:42.556689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5707e6531fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_code', sa.String(length=32), nullable=False),
    sa.Column('parent_agent_id', sa.Integer(), nullable=True),
    sa.Column('traffic_quota_bytes', sa.BigInteger(), nullable=False),
    sa.Column('traffic_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('total_commission_earned', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_agent_user_id', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_code', name='uq_agents_code'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index('ix_agents_is_active', ['is_active'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operator_role', sa.String(length=32), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action_type', ['action_type'], unique=False)
        batch_op.create_index('ix_audit_timestamp', ['timestamp'], unique=False)

    op.create_table('banned_ips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Enum('FAILED_LOGIN', 'ANOMALOUS_HANDSHAKE', 'ACTIVE_PROBE', 'MANUAL', 'RATE_LIMIT', 'CONCURRENT_ABUSE', 'TRAFFIC_ANOMALY', name='banreason'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('strike_count', sa.Integer(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_hash', name='uq_banned_ips_ip_hash')
    )
    with op.batch_alter_table('banned_ips', schema=None) as batch_op:
        batch_op.create_index('ix_banned_ips_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_banned_ips_reason', ['reason'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('protocol', sa.Enum('VLESS_REALITY', 'HYSTERIA2', 'TUIC_V5', 'AMNEZIA_WG', 'SHADOWSOCKS', 'DNSTT', 'ICMP_TUNNEL', name='nodeprotocol'), nullable=False),
    sa.Column('tls_cert_path', sa.String(length=512), nullable=True),
    sa.Column('tls_key_path', sa.String(length=512), nullable=True),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('reality_public_key', sa.String(length=256), nullable=True),
    sa.Column('reality_private_key', sa.String(length=256), nullable=True),
    sa.Column('reality_short_id', sa.String(length=64), nullable=True),
    sa.Column('sni', sa.String(length=256), nullable=True),
    sa.Column('floating_ip', sa.String(length=64), nullable=True),
    sa.Column('cloud_provider', sa.String(length=64), nullable=True),
    sa.Column('cloud_instance_id', sa.String(length=128), nullable=True),
    sa.Column('port_pool_low', sa.String(length=256), nullable=False),
    sa.Column('port_pool_high_start', sa.Integer(), nullable=False),
    sa.Column('port_pool_high_end', sa.Integer(), nullable=False),
    sa.Column('port_hop_interval_sec', sa.Integer(), nullable=False),
    sa.Column('amnezia_jc', sa.Integer(), nullable=False),
    sa.Column('amnezia_jmin', sa.Integer(), nullable=False),
    sa.Column('amnezia_jmax', sa.Integer(), nullable=False),
    sa.Column('amnezia_s1', sa.Integer(), nullable=False),
    sa.Column('amnezia_s2', sa.Integer(), nullable=False),
    sa.Column('amnezia_h1', sa.Integer(), nullable=False),
    sa.Column('amnezia_h2', sa.Integer(), nullable=False),
    sa.Column('amnezia_h3', sa.Integer(), nullable=False),
    sa.Column('amnezia_h4', sa.Integer(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=False),
    sa.Column('current_connections', sa.Integer(), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_nodes_name')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index('ix_nodes_is_active', ['is_active'], unique=False)

    op.create_table('processed_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processed_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_transactions_tx_hash'), ['tx_hash'], unique=True)

    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_system_config_key')
    )
    op.create_table('system_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preset_name', sa.String(length=128), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('active_users_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'COMMISSION', 'TRAFFIC_PURCHASE', 'REFUND', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('encrypted_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_transactions', schema=None) as batch_op:
        batch_op.create_index('ix_agent_tx_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('ix_agent_tx_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_agent_tx_type', ['transaction_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'RESELLER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('data_used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('upload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('download_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bandwidth_limit_mbps', sa.Integer(), nullable=False),
    sa.Column('periodic_reset_strategy', sa.Enum('NO_RESET', 'DAILY', 'WEEKLY', 'MONTHLY', name='periodicresetstrategy'), nullable=False),
    sa.Column('periodic_data_limit_bytes', sa.BigInteger(), nullable=False),
    sa.Column('current_period_usage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_period_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('crypto_address_ton', sa.String(length=128), nullable=True),
    sa.Column('crypto_address_trx', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('private_notes', sa.Text(), nullable=True),
    sa.Column('last_known_ip', sa.Text(), nullable=True),
    sa.Column('gamer_mode', sa.Boolean(), nullable=False),
    sa.Column('battery_saver', sa.Boolean(), nullable=False),
    sa.Column('split_tunnel_bypass', sa.Text(), nullable=True),
    sa.Column('split_tunnel_force', sa.Text(), nullable=True),
    sa.Column('warp_bypass', sa.Boolean(), nullable=False),
    sa.Column('multi_device_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_connections', sa.Integer(), nullable=False),
    sa.Column('shaping_mode', sa.Enum('VIDEO_STREAM', 'VOIP', 'BROWSING', 'RANDOM', 'GAMING', name='shapingmode'), nullable=False),
    sa.Column('tls_fragment_enabled', sa.Boolean(), nullable=False),
    sa.Column('tls_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('host_spoofing_mode', sa.Enum('NONE', 'WS_FRONT', 'CDN_FRONT', 'BUG_INJECTION', name='hostspoofmode'), nullable=False),
    sa.Column('spoofed_host', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_agent_id', ['agent_id'], unique=False)
        batch_op.create_index('ix_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)

    op.create_table('abuse_reputations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('abuse_score', sa.Integer(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('country_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('abuse_reputations', schema=None) as batch_op:
        batch_op.create_index('ix_abuse_status', ['status'], unique=False)
        batch_op.create_index('ix_abuse_user_id', ['user_id'], unique=False)

    op.create_table('connection_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.Text(), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('bytes_up', sa.BigInteger(), nullable=False),
    sa.Column('bytes_down', sa.BigInteger(), nullable=False),
    sa.Column('handshake_status', sa.Enum('SUCCESS', 'TIMEOUT', 'TLS_MISMATCH', 'REPLAY_DETECTED', 'DPI_BLOCKED', 'UNKNOWN_FAILURE', name='handshakestatus'), nullable=False),
    sa.Column('protocol_used', sa.String(length=64), nullable=True),
    sa.Column('handshake_duration_ms', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('is_active_session', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connection_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_logs_client_ip_hash'), ['client_ip_hash'], unique=False)
        batch_op.create_index('ix_connlog_connected_at', ['connected_at'], unique=False)
        batch_op.create_index('ix_connlog_handshake', ['handshake_status'], unique=False)
        batch_op.create_index('ix_connlog_node_id', ['node_id'], unique=False)
        batch_op.create_index('ix_connlog_user_id', ['user_id'], unique=False)

    op.create_table('login_tracker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username_attempted', sa.String(length=128), nullable=False),
    sa.Column('source_ip', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'WRONG_PASSWORD', 'USER_NOT_FOUND', 'ACCOUNT_DISABLED', 'RATE_LIMITED', 'BANNED_IP', name='loginresult'), nullable=False),
    sa.Column('failure_reason', sa.String(length=256), nullable=True),
    sa.Column('geo_country', sa.String(length=4), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_tracker', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempted_at', ['attempted_at'], unique=False)
        batch_op.create_index('ix_login_ip_hash', ['ip_hash'], unique=False)
        batch_op.create_index('ix_login_result', ['result'], unique=False)
        batch_op.create_index('ix_login_user_id', ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('protocols', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('iran_bypass', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_subscriptions_token')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscriptions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index('ix_subscriptions_user_id')

    op.drop_table('subscriptions')
    with op.batch_alter_table('login_tracker', schema=None) as batch_op:
        batch_op.drop_index('ix_login_user_id')
        batch_op.drop_index('ix_login_result')
        batch_op.drop_index('ix_login_ip_hash')
        batch_op.drop_index('ix_login_attempted_at')

    op.drop_table('login_tracker')
    with op.batch_alter_table('connection_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_connlog_user_id')
        batch_op.drop_index('ix_connlog_node_id')
        batch_op.drop_index('ix_connlog_handshake')
        batch_op.drop_index('ix_connlog_connected_at')
        batch_op.drop_index(batch_op.f('ix_connection_logs_client_ip_hash'))

    op.drop_table('connection_logs')
    with op.batch_alter_table('abuse_reputations', schema=None) as batch_op:
        batch_op.drop_index('ix_abuse_user_id')
        batch_op.drop_index('ix_abuse_status')

    op.drop_table('abuse_reputations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_index('ix_users_agent_id')

    op.drop_table('users')
    with op.batch_alter_table('agent_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_tx_type')
        batch_op.drop_index('ix_agent_tx_created_at')
        batch_op.drop_index('ix_agent_tx_agent_id')

    op.drop_table('agent_transactions')
    op.drop_table('system_snapshots')
    op.drop_table('system_config')
    with op.batch_alter_table('processed_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_transactions_tx_hash'))

    op.drop_table('processed_transactions')
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_nodes_is_active')

    op.drop_table('nodes')
    with op.batch_alter_table('banned_ips', schema=None) as batch_op:
        batch_op.drop_index('ix_banned_ips_reason')
        batch_op.drop_index('ix_banned_ips_expires_at')

    op.drop_table('banned_ips')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_timestamp')
        batch_op.drop_index('ix_audit_action_type')

    op.drop_table('audit_logs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index('ix_agents_is_active')

    op.drop_table('agents')
    # ### end Alembic commands ###
